version: '3'

services:
  nginx-proxy:
    image: mesudip/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
  usvad:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      - VIRTUAL_HOST=focus.localtest.me
      - USVA_SEEDS=localhost
    networks:
      - frontend
    extra_hosts:
      - focus.localtest.me:192.168.65.2

  usva:
    build:
      context: .
      x-bake:
        tags:
          - mattipaksula/usva-focus
        platforms:
          - linux/amd64
          - linux/arm64

networks:
  frontend:
    name: frontend
