FROM golang:1.17-alpine3.15

RUN go install github.com/cespare/reflex@latest
RUN apk add --no-cache \
  bash redis curl

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
RUN go mod tidy

COPY . .
EXPOSE 8080
ENTRYPOINT [ "/app/entrypoint-dev.sh" ]
