---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usvad-galant
spec:
  selector:
    matchLabels:
      app: usvad-galant
  template:
    metadata:
      labels:
        app: usvad-galant
    spec:
      containers:
        - name: usvad-galant
          image: mattipaksula/usvad-galant
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 128Mi
          env:
            - name: USVA_ADDRESS
              value: galant.usva.io
