---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usva-focus
spec:
  selector:
    matchLabels:
      app: usva-focus
  template:
    metadata:
      labels:
        app: usva-focus
    spec:
      containers:
        - name: usva-focus
          image: mattipaksula/usva-focus
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 128Mi
          env:
            - name: USVA_ADDRESS
              value: focus.usva.io
