---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usvad-focus
spec:
  ingressClassName: nginx
  rules:
    - host: focus.usva.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: usvad-focus
                port:
                  number: 80
